-- 2단계: BILLING_MASTER (수납 기준정보) 10건
INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000001', 'SVC001', 'FEE001', '일반진찰료', '18660', 'CONSULT', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000002', 'SVC002', 'FEE002', '혈액검사료', '12500', 'LAB', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000003', 'SVC003', 'FEE003', '단순흉부방사선촬영료', '9800', 'RADIOLOGY', 'NON_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000004', 'SVC004', 'FEE004', '심전도검사료', '15400', 'LAB', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000005', 'SVC005', 'FEE005', '초음파검사료(복부)', '62000', 'RADIOLOGY', 'NON_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000006', 'SVC006', 'FEE006', '근육주사료', '3200', 'INJECTION', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000007', 'SVC007', 'FEE007', '정맥주사료', '4500', 'INJECTION', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000008', 'SVC008', 'FEE008', '물리치료료', '21000', 'PHYSICAL_THERAPY', 'NON_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000009', 'SVC009', 'FEE009', '입원료(일반병실)', '45000', 'ADMISSION_FEE', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

INSERT INTO BILLING.BILLING_MASTER
  (BILLING_MASTER_ID, SOURCE_SERVICE_CODE, FEE_CODE, FEE_NAME, DEFAULT_PRICE, CATEGORY_CODE, INSURANCE_TYPE_CODE, EFFECTIVE_FROM, EFFECTIVE_TO, USE_YN)
VALUES
  ('BM00000010', 'SVC010', 'FEE010', '충수절제술', '1250000', 'SURGERY', 'HEALTH_INS', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'Y');

COMMIT;
